### PR TITLE
new delimiter setting

### PR DESCRIPTION
**Pull request by bartocc**
This is the first time I hack on ST plugins so I might have done dumb things ;-)

### CODE REVIEW

**Comment by calwalker1** [comment]
Hey guys, loving this idea. I'm trying to work out where the delimiter setting is as a result of this. I cannot seem to find in my application or user preferences in Sublime.

**Comment by wadetb** [comment]
Hi, you can just copy the setting out of this file:

https://github.com/wadetb/Sublime-Text-Advanced-CSV/blob/master/AdvancedCSV.sublime-settings

The key you want is "delimiter".

I'm not sure why it doesn't open up AdvancedCSV.sublime-settings when you select Package Settings -> Advanced CSV -> Settings - Default

**Comment by calwalker1** [comment]
My apologies, I have since found the settings for this application and it appears to be working well. Very useful tool. Am I able to suggest a feature that essentially spaces out the CSV in a temporary document so it looks like a table within sublime? I know some VBA but haven't tried to do sublime coding yet. So I thought I'd put the idea forward before trying it myself!

**Comment by wadetb** [comment]
Oh glad to hear you got it working.  About spacing out the CSV, have you tried "Format Cells"?  It's bound to Ctrl+comma + Ctrl+space by default.  It works destructively, but you can always re-collapse with Ctrl+comma Ctrl+comma.

**Comment by calwalker1** [comment]
This is extremely embarrassing again. That is the exact function I'm after.
My job involves heaps of CSVs that only need reviewing, they don't need to
go into Excel. So this is a fantastic little tool.

**Pull request merged**
